export const CountdownScene = "countdown"
export const TransitionFromScene = "transition-from"
export const TransitionToScene = "transition-to"
export const TypewriterScene = "typewriter"
export const ProgressBarScene = "progress-bar"
export const WebFontFileScene = "webfontfile"
